name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Publish with dotnet
      run: |
          dotnet publish ChatterConsole -r win-x64 -c Release -o ./win-x64 /p:PublishSingleFile=true
          dotnet publish ChatterConsole -r linux-x64 -c Release -o ./linux-x64 /p:PublishSingleFile=true
          dotnet publish ChatterConsole -r osx-x64 -c Release -o ./osx-x64 /p:PublishSingleFile=true      
